---
  - name: stop tomcat
    service:
      name: tomcat7
      state: stopped

  - name: restart tomcat
    service:
      name: tomcat7
      state: restarted

  - name: restart nginx
    service:
      name: nginx
      state: restarted
